name: Handle submodule update
on:
  repository_dispatch:
    types: [update-submodule]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULES_SYNC }}
      - run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - run: |
          git submodule update --remote ${{ github.event.client_payload.submodule }}
          git add ${{ github.event.client_payload.submodule }}
          git diff --staged --quiet || (
            msg=$(cd ${{ github.event.client_payload.submodule }} && git log -1 --pretty=format:"%s")
            git commit -m "chore: update ${{ github.event.client_payload.submodule }} — $msg [skip ci]" &&
            git push
          )
